-- Improved verification table schema
-- This includes all necessary fields for proper Didit verification tracking

-- Step 1: Add new columns to existing table (migration)
ALTER TABLE public.verification
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS didit_session_id text,
  ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS verification_url text,
  ADD COLUMN IF NOT EXISTS error_message text,
  ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;

-- Step 2: Keep status as text (no constraints)
-- Status remains flexible to accommodate any status values from Didit API
-- No enum or CHECK constraint needed - allows for future status values from Didit

-- Step 3: Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_verification_uuid ON public.verification(uuid);
CREATE INDEX IF NOT EXISTS idx_verification_status ON public.verification(status);
CREATE INDEX IF NOT EXISTS idx_verification_session_id ON public.verification(session_id);
CREATE INDEX IF NOT EXISTS idx_verification_didit_session_id ON public.verification(didit_session_id) WHERE didit_session_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_verification_created_at ON public.verification(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_verification_uuid_status ON public.verification(uuid, status);

-- Step 4: Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_verification_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 5: Create trigger to auto-update updated_at
DROP TRIGGER IF EXISTS trigger_update_verification_updated_at ON public.verification;
CREATE TRIGGER trigger_update_verification_updated_at
  BEFORE UPDATE ON public.verification
  FOR EACH ROW
  EXECUTE FUNCTION update_verification_updated_at();

-- Step 6: Add comments for documentation
COMMENT ON TABLE public.verification IS 'Stores identity verification records from external services like Didit';
COMMENT ON COLUMN public.verification.session_id IS 'Internal session ID generated by the app';
COMMENT ON COLUMN public.verification.didit_session_id IS 'Session ID returned by Didit API (external reference)';
COMMENT ON COLUMN public.verification.status IS 'Verification status from Didit API (text, no constraints - flexible for any status values)';
COMMENT ON COLUMN public.verification.verification_url IS 'URL to complete verification (from Didit)';
COMMENT ON COLUMN public.verification.completed_at IS 'Timestamp when verification was completed (verified or rejected)';
COMMENT ON COLUMN public.verification.expires_at IS 'Timestamp when verification session expires';
COMMENT ON COLUMN public.verification.error_message IS 'Error message if verification failed';
COMMENT ON COLUMN public.verification.metadata IS 'Additional JSON data from Didit API response';

-- Step 7: Enable Row Level Security (RLS)
-- Note: RLS policies are created in a separate file: verification_rls_policies.sql
-- Run that file after this migration to set up proper security policies
ALTER TABLE public.verification ENABLE ROW LEVEL SECURITY;

